export enum URLS_API {
  BASE = "https://ya-praktikum.tech/api/v2",
  AUTH = "/auth",
  SIGNIN = "/signin",
  SIGNUP = "/signup",
  LOGOUT = "/logout",
  CHATS = "/chats",
  GET_CHATS = "",
  CREATE_CHAT = "",
  USER = "/user",
  USERS = "/users",
  SEARCH_USER = "/search",
  PROFILE = "/profile",
  AVATAR = "/avatar",
  PASSWORD = "/password",
  RESOURCES = "/resources",
  TOKEN = "/token",
  WEBSOCKET  = "wss://ya-praktikum.tech/ws",
  COUNT_OF_NEW_MESSAGES = "/new"
}